# Generated by Django 3.0.6 on 2020-08-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body1',
            field=models.TextField(blank=True, null=True, verbose_name='Article Body (optional)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subheading1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Heading (optional)'),
        ),
    ]
